<template>
  <div>
    <div v-for="(item,index) in dataList" :key="index">
        <el-table
      :data="item.childList"
      :span-method="arraySpanMethod"
      border
      style="width: 100%">
      <el-table-column
        prop="ypname"
        label="名称">
      </el-table-column>
      <el-table-column
        prop="grade"
        label="规格编号">
      </el-table-column>
    </el-table>
    </div>
    
  </div>
</template>

<script>
export default {
  name: "hbtable",
  data() {
    return {
      dataList: [
        {
          labtype: null,
          ypid: null,
          ypname: "姘存偿",
          grade: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁?宸ョ▼",
          gradeid: null,
          cjzl: null,
          cjname: null,
          cjzs: null,
          cjhgzs: null,
          zpc: null,
          zl: null,
          jczs: null,
          hgzs: null,
          sybw: null,
          zhgl: null,
          cjhgl: null,
          fbgcname: null,
          childList: [
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "512.2",
              cjname: "璞″北娴疯灪姘存偿鏈夐檺璐ｄ换鍏徃",
              cjzs: "1",
              cjhgzs: "1",
              zpc: null,
              zl: "512.2",
              jczs: "1",
              hgzs: "1",
              sybw: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁?宸ョ▼",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
          ],
          startDate: null,
          endDate: null,
        },
        {
          labtype: null,
          ypid: null,
          ypname: "姘存偿",
          grade:
            "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋?(C1)绛瑰缓鏈熸礊瀹ゅ強閬撹矾宸ョ▼(Q3)",
          gradeid: null,
          cjzl: null,
          cjname: null,
          cjzs: null,
          cjhgzs: null,
          zpc: null,
          zl: null,
          jczs: null,
          hgzs: null,
          sybw: null,
          zhgl: null,
          cjhgl: null,
          fbgcname: null,
          childList: [
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "405.68",
              cjname: "璞″北娴疯灪姘存偿鏈夐檺璐ｄ换鍏徃",
              cjzs: "1",
              cjhgzs: "1",
              zpc: null,
              zl: "405.68",
              jczs: "1",
              hgzs: "1",
              sybw: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋?(C1)绛瑰缓鏈熸礊瀹ゅ強閬撹矾宸ョ▼(Q3)",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
          ],
          startDate: null,
          endDate: null,
        },
        {
          labtype: null,
          ypid: null,
          ypname: "姘存偿",
          grade: " 鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋?",
          gradeid: null,
          cjzl: null,
          cjname: null,
          cjzs: null,
          cjhgzs: null,
          zpc: null,
          zl: null,
          jczs: null,
          hgzs: null,
          sybw: null,
          zhgl: null,
          cjhgl: null,
          fbgcname: null,
          childList: [
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "904.62",
              cjname: "璞″北娴疯灪姘存偿鏈夐檺璐ｄ换鍏徃",
              cjzs: "9",
              cjhgzs: "9",
              zpc: null,
              zl: "904.62",
              jczs: "9",
              hgzs: "9",
              sybw: " 鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋?",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
          ],
          startDate: null,
          endDate: null,
        },
        {
          labtype: null,
          ypid: null,
          ypname: "姘存偿",
          grade: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭叕鍙?",
          gradeid: null,
          cjzl: null,
          cjname: null,
          cjzs: null,
          cjhgzs: null,
          zpc: null,
          zl: null,
          jczs: null,
          hgzs: null,
          sybw: null,
          zhgl: null,
          cjhgl: null,
          fbgcname: null,
          childList: [
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "316.78",
              cjname: "璞″北娴疯灪姘存偿鏈夐檺璐ｄ换鍏徃",
              cjzs: "1",
              cjhgzs: "1",
              zpc: null,
              zl: "316.78",
              jczs: "1",
              hgzs: "1",
              sybw: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭叕鍙?",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
          ],
          startDate: null,
          endDate: null,
        },
        {
          labtype: null,
          ypid: null,
          ypname: "姘存偿",
          grade: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋媆t\t\t",
          gradeid: null,
          cjzl: null,
          cjname: null,
          cjzs: null,
          cjhgzs: null,
          zpc: null,
          zl: null,
          jczs: null,
          hgzs: null,
          sybw: null,
          zhgl: null,
          cjhgl: null,
          fbgcname: null,
          childList: [
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "21016.94",
              cjname: "璞″北娴疯灪姘存偿鏈夐檺璐ｄ换鍏徃",
              cjzs: "127",
              cjhgzs: "126",
              zpc: null,
              zl: "21016.94",
              jczs: "128",
              hgzs: "127",
              sybw: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋媆t\t\t",
              zhgl: "99.2%",
              cjhgl: "99.2%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "0.0",
              cjname: "瀹佹捣寮鸿洘娴疯灪姘存偿鏈夐檺鍏徃",
              cjzs: "1",
              cjhgzs: "1",
              zpc: null,
              zl: "21016.94",
              jczs: "128",
              hgzs: "127",
              sybw: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋媆t\t\t",
              zhgl: "99.2%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
          ],
          startDate: null,
          endDate: null,
        },
        {
          labtype: null,
          ypid: null,
          ypname: "姘存偿",
          grade: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋?",
          gradeid: null,
          cjzl: null,
          cjname: null,
          cjzs: null,
          cjhgzs: null,
          zpc: null,
          zl: null,
          jczs: null,
          hgzs: null,
          sybw: null,
          zhgl: null,
          cjhgl: null,
          fbgcname: null,
          childList: [
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "114094.33",
              cjname: "璞″北娴疯灪姘存偿鏈夐檺璐ｄ换鍏徃",
              cjzs: "588",
              cjhgzs: "588",
              zpc: null,
              zl: "114288.89",
              jczs: "597",
              hgzs: "597",
              sybw: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋?",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "0.1",
              cjname: "瀹佹捣寮鸿洘娴疯灪姘存偿鏈夐檺鍏徃",
              cjzs: "1",
              cjhgzs: "1",
              zpc: null,
              zl: "114288.89",
              jczs: "597",
              hgzs: "597",
              sybw: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋?",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "72.0",
              cjname: "璞″北娴疯灪姘存偿鏈夐檺鍏徃",
              cjzs: "4",
              cjhgzs: "4",
              zpc: null,
              zl: "114288.89",
              jczs: "597",
              hgzs: "597",
              sybw: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋?",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "0.5",
              cjname: "娴欐睙绾㈢嫯姘存偿鑲′唤鏈夐檺鍏徃",
              cjzs: "1",
              cjhgzs: "1",
              zpc: null,
              zl: "114288.89",
              jczs: "597",
              hgzs: "597",
              sybw: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋?",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "P鈪?25",
              gradeid: null,
              cjzl: "121.96",
              cjname: "瀹佹捣寮鸿洘娴疯灪姘存偿鏈夐檺鍏徃",
              cjzs: "3",
              cjhgzs: "3",
              zpc: null,
              zl: "114288.89",
              jczs: "597",
              hgzs: "597",
              sybw: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋?",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
          ],
          startDate: null,
          endDate: null,
        },
        {
          labtype: null,
          ypid: null,
          ypname: "姘存偿",
          grade: "绛瑰缓鏈熸礊瀹ゅ強閬撹矾宸ョ▼",
          gradeid: null,
          cjzl: null,
          cjname: null,
          cjzs: null,
          cjhgzs: null,
          zpc: null,
          zl: null,
          jczs: null,
          hgzs: null,
          sybw: null,
          zhgl: null,
          cjhgl: null,
          fbgcname: null,
          childList: [
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "753.06",
              cjname: "璞″北娴疯灪姘存偿鏈夐檺鍏徃",
              cjzs: "4",
              cjhgzs: "4",
              zpc: null,
              zl: "167787.6",
              jczs: "754",
              hgzs: "754",
              sybw: "绛瑰缓鏈熸礊瀹ゅ強閬撹矾宸ョ▼",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "164916.2",
              cjname: "璞″北娴疯灪姘存偿鏈夐檺璐ｄ换鍏徃",
              cjzs: "684",
              cjhgzs: "684",
              zpc: null,
              zl: "167787.6",
              jczs: "754",
              hgzs: "754",
              sybw: "绛瑰缓鏈熸礊瀹ゅ強閬撹矾宸ョ▼",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "P鈪?25",
              gradeid: null,
              cjzl: "147.92",
              cjname: "瀹佹捣寮鸿洘娴疯灪姘存偿鏈夐檺璐ｄ换鍏徃",
              cjzs: "4",
              cjhgzs: "4",
              zpc: null,
              zl: "167787.6",
              jczs: "754",
              hgzs: "754",
              sybw: "绛瑰缓鏈熸礊瀹ゅ強閬撹矾宸ョ▼",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "P鈪?25",
              gradeid: null,
              cjzl: "1970.42",
              cjname: "瀹佹捣寮鸿洘娴疯灪姘存偿鏈夐檺鍏徃",
              cjzs: "62",
              cjhgzs: "62",
              zpc: null,
              zl: "167787.6",
              jczs: "754",
              hgzs: "754",
              sybw: "绛瑰缓鏈熸礊瀹ゅ強閬撹矾宸ョ▼",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
          ],
          startDate: null,
          endDate: null,
        },
        {
          labtype: null,
          ypid: null,
          ypname: "姘存偿",
          grade:
            "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋?锛圕1鏍囷級锛岀寤烘湡娲炲鍙婇亾璺伐绋?锛圦3鏍囷級",
          gradeid: null,
          cjzl: null,
          cjname: null,
          cjzs: null,
          cjhgzs: null,
          zpc: null,
          zl: null,
          jczs: null,
          hgzs: null,
          sybw: null,
          zhgl: null,
          cjhgl: null,
          fbgcname: null,
          childList: [
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "405.88",
              cjname: "璞″北娴疯灪姘存偿鏈夐檺璐ｄ换鍏徃",
              cjzs: "1",
              cjhgzs: "1",
              zpc: null,
              zl: "405.88",
              jczs: "1",
              hgzs: "1",
              sybw: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋?锛圕1鏍囷級锛岀寤烘湡娲炲鍙婇亾璺伐绋?锛圦3鏍囷級",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
          ],
          startDate: null,
          endDate: null,
        },
        {
          labtype: null,
          ypid: null,
          ypname: "姘存偿",
          grade:
            "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋婥1锛岀寤烘湡娲炲鍙婇亾璺伐绋婹3",
          gradeid: null,
          cjzl: null,
          cjname: null,
          cjzs: null,
          cjhgzs: null,
          zpc: null,
          zl: null,
          jczs: null,
          hgzs: null,
          sybw: null,
          zhgl: null,
          cjhgl: null,
          fbgcname: null,
          childList: [
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "920.74",
              cjname: "璞″北娴疯灪姘存偿鏈夐檺璐ｄ换鍏徃",
              cjzs: "2",
              cjhgzs: "2",
              zpc: null,
              zl: "920.74",
              jczs: "2",
              hgzs: "2",
              sybw: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋婥1锛岀寤烘湡娲炲鍙婇亾璺伐绋婹3",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
          ],
          startDate: null,
          endDate: null,
        },
        {
          labtype: null,
          ypid: null,
          ypname: "姘存偿",
          grade: "鍦熷缓鍙婇噾灞炴満鏋勫畨瑁呭伐绋?",
          gradeid: null,
          cjzl: null,
          cjname: null,
          cjzs: null,
          cjhgzs: null,
          zpc: null,
          zl: null,
          jczs: null,
          hgzs: null,
          sybw: null,
          zhgl: null,
          cjhgl: null,
          fbgcname: null,
          childList: [
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "20.0",
              cjname: "璞″北娴疯灪姘存偿鏈夐檺璐ｄ换鍏徃",
              cjzs: "1",
              cjhgzs: "1",
              zpc: null,
              zl: "20.0",
              jczs: "1",
              hgzs: "1",
              sybw: "鍦熷缓鍙婇噾灞炴満鏋勫畨瑁呭伐绋?",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
          ],
          startDate: null,
          endDate: null,
        },
        {
          labtype: null,
          ypid: null,
          ypname: "姘存偿",
          grade:
            "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋嬶紙C1锛?绛瑰缓鏈熸礊瀹ゅ強閬撹矾宸ョ▼(Q3)",
          gradeid: null,
          cjzl: null,
          cjname: null,
          cjzs: null,
          cjhgzs: null,
          zpc: null,
          zl: null,
          jczs: null,
          hgzs: null,
          sybw: null,
          zhgl: null,
          cjhgl: null,
          fbgcname: null,
          childList: [
            {
              labtype: null,
              ypid: null,
              ypname: "姘存偿",
              grade: "PO425",
              gradeid: null,
              cjzl: "736.44",
              cjname: "璞″北娴疯灪姘存偿鏈夐檺璐ｄ换鍏徃",
              cjzs: "2",
              cjhgzs: "2",
              zpc: null,
              zl: "736.44",
              jczs: "2",
              hgzs: "2",
              sybw: "鍦熷缓鍙婇噾灞炵粨鏋勫畨瑁呭伐绋嬶紙C1锛?绛瑰缓鏈熸礊瀹ゅ強閬撹矾宸ョ▼(Q3)",
              zhgl: "100.0%",
              cjhgl: "100.0%",
              fbgcname: null,
              childList: null,
              startDate: null,
              endDate: null,
            },
          ],
          startDate: null,
          endDate: null,
        },
      ],
    };
  },
  methods: {
     arraySpanMethod({ row, column, rowIndex, columnIndex }) {
        console.log(row, column);
        if (rowIndex % 2 === 0) {
          if (columnIndex === 0) {
            return [1, 2];
          } else if (columnIndex === 1) {
            return [0, 0];
          }
        }
      }
  },
};
</script>