<template>
  <div>
      <div style="height:200px" id="line"></div>
  </div>
</template>
<script>
export default {
    name:"no0echarts",
  data() {
    return {
      data: {
        reportId: null,
        jcxm: null,
        sampleName: null,
        model: null,
        packing: null,
        grade: null,
        resultvalue: null,
        maxValue: "300.0",
        compareType: null,
        ckitemName: "下屈服强度",
        section: null,
        frequency: null,
        xaxis: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        yaxis: "455",
        itemName: null,
        zjcpType: null,
        fullName: "20(mm)HPB300",
        bean: [
          {
            reportId: "d4407c4a01d34db7acc27c0b2fa2d5c0",
            jcxm: "拉伸试验、弯曲试验、重量偏差",
            sampleName: "钢筋",
            model: "20(mm)",
            packing: "",
            grade: "HPB300",
            resultvalue: "360",
            maxValue: "300.0",
            compareType: "D",
            ckitemName: "下屈服强度",
            section: null,
            frequency: null,
            xaxis: null,
            yaxis: null,
            itemName: null,
            zjcpType: null,
            fullName: "20(mm)HPB300",
            bean: null,
          },
          {
            reportId: "061d4f30ba7f4529b354e43d77fd6451",
            jcxm: "拉伸试验、弯曲试验、重量偏差",
            sampleName: "钢筋",
            model: "20(mm)",
            packing: "",
            grade: "HPB300",
            resultvalue: "420",
            maxValue: "300.0",
            compareType: "D",
            ckitemName: "下屈服强度",
            section: null,
            frequency: null,
            xaxis: null,
            yaxis: null,
            itemName: null,
            zjcpType: null,
            fullName: "20(mm)HPB300",
            bean: null,
          },
          {
            reportId: "1c9b154ef4a94a9d93f46431b03c7ffe",
            jcxm: "拉伸试验、弯曲试验、重量偏差",
            sampleName: "钢筋",
            model: "20(mm)",
            packing: "",
            grade: "HPB300",
            resultvalue: "425",
            maxValue: "300.0",
            compareType: "D",
            ckitemName: "下屈服强度",
            section: null,
            frequency: null,
            xaxis: null,
            yaxis: null,
            itemName: null,
            zjcpType: null,
            fullName: "20(mm)HPB300",
            bean: null,
          },
          {
            reportId: "be11594a44344de58fe95d4ef0e9c231",
            jcxm: "拉伸试验、弯曲试验、重量偏差",
            sampleName: "钢筋",
            model: "20(mm)",
            packing: "",
            grade: "HPB300",
            resultvalue: "360",
            maxValue: "300.0",
            compareType: "D",
            ckitemName: "下屈服强度",
            section: null,
            frequency: null,
            xaxis: null,
            yaxis: null,
            itemName: null,
            zjcpType: null,
            fullName: "20(mm)HPB300",
            bean: null,
          },
          {
            reportId: "af6a9182e4e9498c850e3efb84c5f386",
            jcxm: "拉伸试验、弯曲试验、重量偏差",
            sampleName: "钢筋",
            model: "20(mm)",
            packing: "",
            grade: "HPB300",
            resultvalue: "360",
            maxValue: "300.0",
            compareType: "D",
            ckitemName: "下屈服强度",
            section: null,
            frequency: null,
            xaxis: null,
            yaxis: null,
            itemName: null,
            zjcpType: null,
            fullName: "20(mm)HPB300",
            bean: null,
          },
          {
            reportId: "a13039a7754d438b894482d1e487dc1c",
            jcxm: "拉伸试验、弯曲试验、重量偏差",
            sampleName: "钢筋",
            model: "20(mm)",
            packing: "",
            grade: "HPB300",
            resultvalue: "360",
            maxValue: "300.0",
            compareType: "D",
            ckitemName: "下屈服强度",
            section: null,
            frequency: null,
            xaxis: null,
            yaxis: null,
            itemName: null,
            zjcpType: null,
            fullName: "20(mm)HPB300",
            bean: null,
          },
          {
            reportId: "2f0dc84ed93f40e6bba3e4e57351d184",
            jcxm: "拉伸试验、弯曲试验、重量偏差",
            sampleName: "钢筋",
            model: "20(mm)",
            packing: "",
            grade: "HPB300",
            resultvalue: "425",
            maxValue: "300.0",
            compareType: "D",
            ckitemName: "下屈服强度",
            section: null,
            frequency: null,
            xaxis: null,
            yaxis: null,
            itemName: null,
            zjcpType: null,
            fullName: "20(mm)HPB300",
            bean: null,
          },
          {
            reportId: "d8580fb80c8a49ff84abc9f90dbccde1",
            jcxm: "拉伸试验、弯曲试验、重量偏差",
            sampleName: "钢筋",
            model: "20(mm)",
            packing: "",
            grade: "HPB300",
            resultvalue: "455",
            maxValue: "300.0",
            compareType: "D",
            ckitemName: "下屈服强度",
            section: null,
            frequency: null,
            xaxis: null,
            yaxis: null,
            itemName: null,
            zjcpType: null,
            fullName: "20(mm)HPB300",
            bean: null,
          },
          {
            reportId: "31cd47712f9248ee958927a3203674b4",
            jcxm: "拉伸试验、弯曲试验、重量偏差",
            sampleName: "钢筋",
            model: "20(mm)",
            packing: "",
            grade: "HPB300",
            resultvalue: "0",
            maxValue: "300.0",
            compareType: "D",
            ckitemName: "下屈服强度",
            section: null,
            frequency: null,
            xaxis: null,
            yaxis: null,
            itemName: null,
            zjcpType: null,
            fullName: "20(mm)HPB300",
            bean: null,
          },
          {
            reportId: "915f4ba8aeaf4f8facfd63a3a802b849",
            jcxm: "拉伸试验、弯曲试验、重量偏差",
            sampleName: "钢筋",
            model: "20(mm)",
            packing: "",
            grade: "HPB300",
            resultvalue: "0",
            maxValue: "300.0",
            compareType: "D",
            ckitemName: "下屈服强度",
            section: null,
            frequency: null,
            xaxis: null,
            yaxis: null,
            itemName: null,
            zjcpType: null,
            fullName: "20(mm)HPB300",
            bean: null,
          },
          {
            reportId: "110e04d6711041e4ac659d8b31fb685e",
            jcxm: "拉伸试验、弯曲试验、重量偏差",
            sampleName: "钢筋",
            model: "20(mm)",
            packing: "",
            grade: "HPB300",
            resultvalue: "0",
            maxValue: "300.0",
            compareType: "D",
            ckitemName: "下屈服强度",
            section: null,
            frequency: null,
            xaxis: null,
            yaxis: null,
            itemName: null,
            zjcpType: null,
            fullName: "20(mm)HPB300",
            bean: null,
          },
          {
            reportId: "0028db9892ab4aa3aca21f353235716c",
            jcxm: "拉伸试验、弯曲试验、重量偏差",
            sampleName: "钢筋",
            model: "20(mm)",
            packing: "",
            grade: "HPB300",
            resultvalue: "0",
            maxValue: "300.0",
            compareType: "D",
            ckitemName: "下屈服强度",
            section: null,
            frequency: null,
            xaxis: null,
            yaxis: null,
            itemName: null,
            zjcpType: null,
            fullName: "20(mm)HPB300",
            bean: null,
          },
          {
            reportId: "731cece70f9d4fc7b29ab2ddcb360f49",
            jcxm: "拉伸试验、弯曲试验、重量偏差",
            sampleName: "钢筋",
            model: "20(mm)",
            packing: "",
            grade: "HPB300",
            resultvalue: "0",
            maxValue: "300.0",
            compareType: "D",
            ckitemName: "下屈服强度",
            section: null,
            frequency: null,
            xaxis: null,
            yaxis: null,
            itemName: null,
            zjcpType: null,
            fullName: "20(mm)HPB300",
            bean: null,
          },
        ],
      },
    };
  },
  mounted(){
      this.drawLine()
  },
  methods:{
      drawLine(){
          console.log(this.$echarts);
          this.$echarts.init(document.getElementById("line"))
      }
  }
};
</script>